services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    expose:
      - "8000"

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  acp-db:
    image: ghcr.io/starflower-sh/sage-postgres:18
    env_file:
      - ./backend/.env
    environment:
      PGDATA: /var/lib/pg-acp/data
    ports:
      - "5432:5432"
    volumes:
      - acp_pg_data:/var/lib/pg-acp/data
    restart: unless-stopped


volumes:
  caddy_data:
  caddy_config:
  acp_pg_data:
